// <auto-generated />
using System;
using Looma.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Looma.Infrastructure.Migrations
{
    [DbContext(typeof(LoomaDbContext))]
    [Migration("20260613165118_UpdateDocumentRelations")]
    partial class UpdateDocumentRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Looma.Infrastructure.Entity.DocumentEntity", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PatternId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("DocumentId");

                    b.HasIndex("PatternId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Documents", t =>
                        {
                            t.HasCheckConstraint("CK_Document_SingleParent", "(\"PatternId\" IS NULL OR \"ProjectId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("Looma.Infrastructure.Entity.PatternEntity", b =>
                {
                    b.Property<int>("PatternId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("BeginDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPersonal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("PatternId");

                    b.ToTable("Patterns");
                });

            modelBuilder.Entity("Looma.Infrastructure.Entity.ProjectEntity", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("BeginDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatternId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectId");

                    b.HasIndex("PatternId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Looma.Infrastructure.Entity.WoolEntity", b =>
                {
                    b.Property<int>("WoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Length")
                        .HasColumnType("REAL");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("NeedleMaxSize")
                        .HasColumnType("REAL");

                    b.Property<double>("NeedleMinSize")
                        .HasColumnType("REAL");

                    b.Property<double>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(1000.0);

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("WoolId");

                    b.ToTable("Wools");
                });

            modelBuilder.Entity("Looma.Infrastructure.Entity.WoolsForProjectEntity", b =>
                {
                    b.Property<int>("WoolId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("StockAlreadyUsed")
                        .HasColumnType("REAL");

                    b.Property<double>("StockUsed")
                        .HasColumnType("REAL");

                    b.HasKey("WoolId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("WoolsForProjects");
                });

            modelBuilder.Entity("Looma.Infrastructure.Entity.DocumentEntity", b =>
                {
                    b.HasOne("Looma.Infrastructure.Entity.PatternEntity", "Pattern")
                        .WithMany("Documents")
                        .HasForeignKey("PatternId");

                    b.HasOne("Looma.Infrastructure.Entity.ProjectEntity", "Project")
                        .WithMany("Files")
                        .HasForeignKey("ProjectId");

                    b.Navigation("Pattern");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Looma.Infrastructure.Entity.ProjectEntity", b =>
                {
                    b.HasOne("Looma.Infrastructure.Entity.PatternEntity", "PatternEntity")
                        .WithMany("Projects")
                        .HasForeignKey("PatternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatternEntity");
                });

            modelBuilder.Entity("Looma.Infrastructure.Entity.WoolsForProjectEntity", b =>
                {
                    b.HasOne("Looma.Infrastructure.Entity.ProjectEntity", "ProjectEntity")
                        .WithMany("WoolsForProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Looma.Infrastructure.Entity.WoolEntity", "WoolEntity")
                        .WithMany("WoolsForProjects")
                        .HasForeignKey("WoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectEntity");

                    b.Navigation("WoolEntity");
                });

            modelBuilder.Entity("Looma.Infrastructure.Entity.PatternEntity", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Looma.Infrastructure.Entity.ProjectEntity", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("WoolsForProjects");
                });

            modelBuilder.Entity("Looma.Infrastructure.Entity.WoolEntity", b =>
                {
                    b.Navigation("WoolsForProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
