// <auto-generated />
using System;
using Looma.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Looma.Infrastructure.Migrations
{
    [DbContext(typeof(LoomaDbContext))]
    [Migration("20260321200801_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("DocumentEntityPatternEntity", b =>
                {
                    b.Property<int>("DocumentsDocumentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatternsPatternId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DocumentsDocumentId", "PatternsPatternId");

                    b.HasIndex("PatternsPatternId");

                    b.ToTable("DocumentPattern", (string)null);
                });

            modelBuilder.Entity("Looma.Infrastructure.Model.DocumentEntity", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nickname")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DocumentId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Looma.Infrastructure.Model.PatternEntity", b =>
                {
                    b.Property<int>("PatternId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("PatternType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("PatternId");

                    b.ToTable("Patterns");
                });

            modelBuilder.Entity("Looma.Infrastructure.Model.ProjectEntity", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("BeginDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PatronId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectId");

                    b.HasIndex("PatronId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Looma.Infrastructure.Model.StockEntity", b =>
                {
                    b.Property<int>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("WeightQuantity")
                        .HasColumnType("REAL");

                    b.Property<int>("WoolId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StockId");

                    b.HasIndex("WoolId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("Looma.Infrastructure.Model.WoolEntity", b =>
                {
                    b.Property<int>("WoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("LengthToWeightRatio")
                        .HasColumnType("REAL");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("WoolId");

                    b.ToTable("Wools");
                });

            modelBuilder.Entity("Looma.Infrastructure.Model.WoolsForProjectEntity", b =>
                {
                    b.Property<int>("WoolId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WoolId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("WoolsForProjects");
                });

            modelBuilder.Entity("DocumentEntityPatternEntity", b =>
                {
                    b.HasOne("Looma.Infrastructure.Model.DocumentEntity", null)
                        .WithMany()
                        .HasForeignKey("DocumentsDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Looma.Infrastructure.Model.PatternEntity", null)
                        .WithMany()
                        .HasForeignKey("PatternsPatternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Looma.Infrastructure.Model.ProjectEntity", b =>
                {
                    b.HasOne("Looma.Infrastructure.Model.PatternEntity", "PatternEntity")
                        .WithMany("Projects")
                        .HasForeignKey("PatronId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatternEntity");
                });

            modelBuilder.Entity("Looma.Infrastructure.Model.StockEntity", b =>
                {
                    b.HasOne("Looma.Infrastructure.Model.WoolEntity", "WoolEntity")
                        .WithMany("Stocks")
                        .HasForeignKey("WoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WoolEntity");
                });

            modelBuilder.Entity("Looma.Infrastructure.Model.WoolsForProjectEntity", b =>
                {
                    b.HasOne("Looma.Infrastructure.Model.ProjectEntity", "ProjectEntity")
                        .WithMany("WoolsForProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Looma.Infrastructure.Model.WoolEntity", "WoolEntity")
                        .WithMany("WoolsForProjects")
                        .HasForeignKey("WoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectEntity");

                    b.Navigation("WoolEntity");
                });

            modelBuilder.Entity("Looma.Infrastructure.Model.PatternEntity", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Looma.Infrastructure.Model.ProjectEntity", b =>
                {
                    b.Navigation("WoolsForProjects");
                });

            modelBuilder.Entity("Looma.Infrastructure.Model.WoolEntity", b =>
                {
                    b.Navigation("Stocks");

                    b.Navigation("WoolsForProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
