<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\Looma.Presentation\Looma.Presentation.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.0.3"/>
        <PackageReference Include="Avalonia.Controls.ColorPicker" Version="12.0.3"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.3"/>
        <PackageReference Include="LiveChartsCore.SkiaSharpView.Avalonia" Version="2.1.0-dev-798" />
        <PackageReference Include="Lucide.Avalonia" Version="0.2.5" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Main\MainWindow.axaml.cs">
            <DependentUpon>MainWindow.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Main\MainWindow.axaml.cs">
            <DependentUpon>MainWindow.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Sections\Projects\ProjectsListView.axaml.cs">
            <DependentUpon>ProjectsListView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <AdditionalFiles Include="Views\Main\MainWindow.axaml"/>
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

</Project>
